both_list = [
    {"url": "https://imgur.com/HQpSdio",
     "text": ""}, 
    {"url": "https://imgur.com/gz1Ufsv",
     "text": ""}, 
    {"url": "https://imgur.com/n18iyHB",
     "text": ""}, 
    {"url": "https://imgur.com/TzaT10h",
     "text": ""}, 
    {"url": "https://imgur.com/4RUh8Mo",
     "text": ""}, 
    {"url": "https://imgur.com/lrzPp36",
     "text": ""}, 
    {"url": "https://imgur.com/Rbo9jce",
     "text": ""}, 
    {"url": "https://imgur.com/6RGl5Kj",
     "text": ""}, 
    {"url": "https://imgur.com/WMhYP39",
     "text": ""}, 
    {"url": "https://imgur.com/PkwAt0H",
     "text": ""}, 
    {"url": "https://imgur.com/brgyU9y",
     "text": ""}, 
    {"url": "https://imgur.com/IErIavw",
     "text": ""}, 
    {"url": "https://imgur.com/sucjh7V",
     "text": ""}, 
    {"url": "https://imgur.com/cfsg5JH",
     "text": ""}, 
    {"url": "https://imgur.com/T5xijO5",
     "text": ""}, 
    {"url": "https://imgur.com/y42zqKr",
     "text": ""}, 
    {"url": "https://imgur.com/kNJ7rrq",
     "text": ""}, 
    {"url": "https://imgur.com/RafG9sW",
     "text": ""}, 
    {"url": "https://imgur.com/N8XkFVl",
     "text": ""}, 
    {"url": "https://imgur.com/55HNC1I",
     "text": ""}, 
    {"url": "https://imgur.com/JjiSmYJ",
     "text": ""}, 
    {"url": "https://imgur.com/gxh0QAf",
     "text": ""}, 
    {"url": "https://imgur.com/VhPX1SR",
     "text": ""}, 
    {"url": "https://imgur.com/0MqpkLl",
     "text": ""}, 
    {"url": "https://imgur.com/KQ1GNS6",
     "text": ""}, 
    {"url": "https://imgur.com/Yzy0LeR",
     "text": ""}, 
    {"url": "https://imgur.com/eYadgJX",
     "text": ""}, 
    {"url": "https://imgur.com/KsB6DMj",
     "text": ""}, 
    {"url": "https://imgur.com/ZZlulQA",
     "text": ""}, 
    {"url": "https://imgur.com/xr7Bw6i",
     "text": ""}, 
    {"url": "https://imgur.com/cdfyt2f",
     "text": ""}, 
    {"url": "https://imgur.com/kkRWfrj",
     "text": ""}, 
    {"url": "https://imgur.com/T8i8HI6",
     "text": ""}, 
    {"url": "https://imgur.com/dAICmjG",
     "text": ""}, 
    {"url": "https://imgur.com/k2xKhF7",
     "text": ""}, 
    {"url": "https://imgur.com/HozjaEX",
     "text": ""}, 
    {"url": "https://imgur.com/1a1U87l",
     "text": ""}, 
    {"url": "https://imgur.com/Yjwk6Jd",
     "text": ""}, 
    {"url": "https://imgur.com/WKmIHsG",
     "text": ""}, 
    {"url": "https://imgur.com/rWkACIl",
     "text": ""}, 
    {"url": "https://imgur.com/Hx4P34K",
     "text": ""}, 
    {"url": "https://imgur.com/OHP0AMC",
     "text": ""}
]

handsome_list = [
    "https://imgur.com/Kn5Pj4c",
    "https://imgur.com/AF3q0kA", 
    "https://imgur.com/WFzHGOc", 
    "https://imgur.com/D3nV72x", 
    "https://imgur.com/ColDGdQ", 
    "https://imgur.com/8N3UHQo", 
    "https://imgur.com/gqHKm3A", 
    "https://imgur.com/wK4MQhO", 
    "https://imgur.com/k1lTxyj", 
    "https://imgur.com/AVXoTcx", 
    "https://imgur.com/7hJQO6C", 
    "https://imgur.com/bgM2fkx", 
    "https://imgur.com/03crKch", 
    "https://imgur.com/VqEpQmT", 
    "https://imgur.com/A2ROHTq"
]